job_id: tree-pruner-06fa6bfb-881c-4294-800c-4d8cb0dd3d09
email: gdicecco@live.unc.edu
tree_base: birdtree
tree_set: EricsonStage2Full
sample_size: 100
names: [Corvus_brachyrhynchos, Corvus_ossifragus, Tachycineta_bicolor, Tachycineta_thalassina,
  Stelgidopteryx_serripennis, Parus_carolinensis, Parus_atricapillus, Parus_gambeli,
  Parus_rufescens, Baeolophus_bicolor, Baeolophus_atricristatus, Auriparus_flaviceps,
  Psaltriparus_minimus, Sitta_canadensis, Sitta_carolinensis, Sitta_pusilla, Salpinctes_obsoletus,
  Troglodytes_troglodytes, Cistothorus_palustris, Thryothorus_ludovicianus, Thryomanes_bewickii,
  Campylorhynchus_brunneicapillus, Polioptila_caerulea, Regulus_satrapa, Sialia_sialis,
  Sialia_currucoides, Myadestes_townsendi, Catharus_ustulatus, Hylocichla_mustelina,
  Turdus_migratorius, Dumetella_carolinensis, Toxostoma_rufum, Oreoscoptes_montanus,
  Mimus_polyglottos, Bombycilla_cedrorum, Carpodacus_mexicanus, Carpodacus_purpureus,
  Carpodacus_cassinii, Carduelis_pinus, Carduelis_psaltria, Carduelis_tristis, Coccothraustes_vespertinus,
  Calcarius_ornatus, Helmitheros_vermivorum, Seiurus_motacilla, Vermivora_chrysoptera,
  Vermivora_pinus, Protonotaria_citrea, Limnothlypis_swainsonii, Vermivora_celata,
  Vermivora_ruficapilla, Wilsonia_citrina, Dendroica_tigrina, Dendroica_cerulea, Dendroica_magnolia,
  Dendroica_castanea, Dendroica_fusca, Dendroica_pensylvanica, Dendroica_caerulescens,
  Dendroica_pinus, Dendroica_dominica, Dendroica_discolor, Dendroica_nigrescens, Dendroica_townsendi,
  Dendroica_virens, Wilsonia_canadensis, Wilsonia_pusilla, Icteria_virens, Pipilo_chlorurus,
  Pipilo_maculatus, Aimophila_ruficeps, Aimophila_cassinii, Spizella_pallida, Spizella_breweri,
  Spizella_pusilla, Pooecetes_gramineus, Chondestes_grammacus, Amphispiza_bilineata,
  Calamospiza_melanocorys, Passerculus_sandwichensis, Ammodramus_savannarum, Ammodramus_henslowii,
  Ammodramus_maritimus, Melospiza_melodia, Melospiza_lincolnii, Melospiza_georgiana,
  Zonotrichia_albicollis, Zonotrichia_leucophrys, Piranga_olivacea, Piranga_ludoviciana,
  Cardinalis_cardinalis, Pheucticus_ludovicianus, Pheucticus_melanocephalus, Passerina_caerulea,
  Passerina_amoena, Passerina_cyanea, Agelaius_phoeniceus, Sturnella_magna, Sturnella_neglecta,
  Xanthocephalus_xanthocephalus, Euphagus_cyanocephalus, Quiscalus_major, Quiscalus_mexicanus,
  Molothrus_ater, Icterus_spurius, Icterus_bullockii, Icterus_galbula]
sample_trees: [EricsonStage2Full_6755.tre, EricsonStage2Full_1072.tre, EricsonStage2Full_1963.tre,
  EricsonStage2Full_7681.tre, EricsonStage2Full_9679.tre, EricsonStage2Full_1106.tre,
  EricsonStage2Full_7123.tre, EricsonStage2Full_6677.tre, EricsonStage2Full_9469.tre,
  EricsonStage2Full_4564.tre, EricsonStage2Full_3714.tre, EricsonStage2Full_4024.tre,
  EricsonStage2Full_7513.tre, EricsonStage2Full_6694.tre, EricsonStage2Full_6635.tre,
  EricsonStage2Full_2050.tre, EricsonStage2Full_9826.tre, EricsonStage2Full_7516.tre,
  EricsonStage2Full_9345.tre, EricsonStage2Full_4462.tre, EricsonStage2Full_2557.tre,
  EricsonStage2Full_3607.tre, EricsonStage2Full_0183.tre, EricsonStage2Full_8151.tre,
  EricsonStage2Full_4933.tre, EricsonStage2Full_0867.tre, EricsonStage2Full_5032.tre,
  EricsonStage2Full_8428.tre, EricsonStage2Full_4978.tre, EricsonStage2Full_6642.tre,
  EricsonStage2Full_0325.tre, EricsonStage2Full_3576.tre, EricsonStage2Full_5245.tre,
  EricsonStage2Full_5357.tre, EricsonStage2Full_4509.tre, EricsonStage2Full_2781.tre,
  EricsonStage2Full_8435.tre, EricsonStage2Full_6124.tre, EricsonStage2Full_1909.tre,
  EricsonStage2Full_3769.tre, EricsonStage2Full_2880.tre, EricsonStage2Full_6585.tre,
  EricsonStage2Full_0951.tre, EricsonStage2Full_4790.tre, EricsonStage2Full_3615.tre,
  EricsonStage2Full_0794.tre, EricsonStage2Full_1201.tre, EricsonStage2Full_5214.tre,
  EricsonStage2Full_8390.tre, EricsonStage2Full_2091.tre, EricsonStage2Full_2287.tre,
  EricsonStage2Full_2285.tre, EricsonStage2Full_7284.tre, EricsonStage2Full_9091.tre,
  EricsonStage2Full_3000.tre, EricsonStage2Full_8815.tre, EricsonStage2Full_2767.tre,
  EricsonStage2Full_7616.tre, EricsonStage2Full_8626.tre, EricsonStage2Full_0085.tre,
  EricsonStage2Full_5970.tre, EricsonStage2Full_3822.tre, EricsonStage2Full_5901.tre,
  EricsonStage2Full_2933.tre, EricsonStage2Full_8328.tre, EricsonStage2Full_6066.tre,
  EricsonStage2Full_9904.tre, EricsonStage2Full_9682.tre, EricsonStage2Full_8971.tre,
  EricsonStage2Full_9113.tre, EricsonStage2Full_7081.tre, EricsonStage2Full_0335.tre,
  EricsonStage2Full_5248.tre, EricsonStage2Full_1040.tre, EricsonStage2Full_7316.tre,
  EricsonStage2Full_3271.tre, EricsonStage2Full_2167.tre, EricsonStage2Full_8524.tre,
  EricsonStage2Full_1820.tre, EricsonStage2Full_2398.tre, EricsonStage2Full_0497.tre,
  EricsonStage2Full_7747.tre, EricsonStage2Full_5157.tre, EricsonStage2Full_0353.tre,
  EricsonStage2Full_7466.tre, EricsonStage2Full_2827.tre, EricsonStage2Full_1920.tre,
  EricsonStage2Full_9125.tre, EricsonStage2Full_1486.tre, EricsonStage2Full_6117.tre,
  EricsonStage2Full_8643.tre, EricsonStage2Full_7866.tre, EricsonStage2Full_5261.tre,
  EricsonStage2Full_1369.tre, EricsonStage2Full_6078.tre, EricsonStage2Full_8788.tre,
  EricsonStage2Full_5867.tre, EricsonStage2Full_3592.tre, EricsonStage2Full_7743.tre,
  EricsonStage2Full_9827.tre]
status: COMPLETED
created_at: "2021-09-29T22:50:51Z"
completed_at: "2021-09-29T22:51:28Z"
bad_names: {EricsonStage2Full_0085.tre: [], EricsonStage2Full_0183.tre: [], EricsonStage2Full_0325.tre: [],
  EricsonStage2Full_0335.tre: [], EricsonStage2Full_0353.tre: [], EricsonStage2Full_0497.tre: [],
  EricsonStage2Full_0794.tre: [], EricsonStage2Full_0867.tre: [], EricsonStage2Full_0951.tre: [],
  EricsonStage2Full_1040.tre: [], EricsonStage2Full_1072.tre: [], EricsonStage2Full_1106.tre: [],
  EricsonStage2Full_1201.tre: [], EricsonStage2Full_1369.tre: [], EricsonStage2Full_1486.tre: [],
  EricsonStage2Full_1820.tre: [], EricsonStage2Full_1909.tre: [], EricsonStage2Full_1920.tre: [],
  EricsonStage2Full_1963.tre: [], EricsonStage2Full_2050.tre: [], EricsonStage2Full_2091.tre: [],
  EricsonStage2Full_2167.tre: [], EricsonStage2Full_2285.tre: [], EricsonStage2Full_2287.tre: [],
  EricsonStage2Full_2398.tre: [], EricsonStage2Full_2557.tre: [], EricsonStage2Full_2767.tre: [],
  EricsonStage2Full_2781.tre: [], EricsonStage2Full_2827.tre: [], EricsonStage2Full_2880.tre: [],
  EricsonStage2Full_2933.tre: [], EricsonStage2Full_3000.tre: [], EricsonStage2Full_3271.tre: [],
  EricsonStage2Full_3576.tre: [], EricsonStage2Full_3592.tre: [], EricsonStage2Full_3607.tre: [],
  EricsonStage2Full_3615.tre: [], EricsonStage2Full_3714.tre: [], EricsonStage2Full_3769.tre: [],
  EricsonStage2Full_3822.tre: [], EricsonStage2Full_4024.tre: [], EricsonStage2Full_4462.tre: [],
  EricsonStage2Full_4509.tre: [], EricsonStage2Full_4564.tre: [], EricsonStage2Full_4790.tre: [],
  EricsonStage2Full_4933.tre: [], EricsonStage2Full_4978.tre: [], EricsonStage2Full_5032.tre: [],
  EricsonStage2Full_5157.tre: [], EricsonStage2Full_5214.tre: [], EricsonStage2Full_5245.tre: [],
  EricsonStage2Full_5248.tre: [], EricsonStage2Full_5261.tre: [], EricsonStage2Full_5357.tre: [],
  EricsonStage2Full_5867.tre: [], EricsonStage2Full_5901.tre: [], EricsonStage2Full_5970.tre: [],
  EricsonStage2Full_6066.tre: [], EricsonStage2Full_6078.tre: [], EricsonStage2Full_6117.tre: [],
  EricsonStage2Full_6124.tre: [], EricsonStage2Full_6585.tre: [], EricsonStage2Full_6635.tre: [],
  EricsonStage2Full_6642.tre: [], EricsonStage2Full_6677.tre: [], EricsonStage2Full_6694.tre: [],
  EricsonStage2Full_6755.tre: [], EricsonStage2Full_7081.tre: [], EricsonStage2Full_7123.tre: [],
  EricsonStage2Full_7284.tre: [], EricsonStage2Full_7316.tre: [], EricsonStage2Full_7466.tre: [],
  EricsonStage2Full_7513.tre: [], EricsonStage2Full_7516.tre: [], EricsonStage2Full_7616.tre: [],
  EricsonStage2Full_7681.tre: [], EricsonStage2Full_7743.tre: [], EricsonStage2Full_7747.tre: [],
  EricsonStage2Full_7866.tre: [], EricsonStage2Full_8151.tre: [], EricsonStage2Full_8328.tre: [],
  EricsonStage2Full_8390.tre: [], EricsonStage2Full_8428.tre: [], EricsonStage2Full_8435.tre: [],
  EricsonStage2Full_8524.tre: [], EricsonStage2Full_8626.tre: [], EricsonStage2Full_8643.tre: [],
  EricsonStage2Full_8788.tre: [], EricsonStage2Full_8815.tre: [], EricsonStage2Full_8971.tre: [],
  EricsonStage2Full_9091.tre: [], EricsonStage2Full_9113.tre: [], EricsonStage2Full_9125.tre: [],
  EricsonStage2Full_9345.tre: [], EricsonStage2Full_9469.tre: [], EricsonStage2Full_9679.tre: [],
  EricsonStage2Full_9682.tre: [], EricsonStage2Full_9826.tre: [], EricsonStage2Full_9827.tre: [],
  EricsonStage2Full_9904.tre: []}
